# This is a basic workflow to help you get started with Actions
# 
name: DotNetCore

# Controls when the action will run. 
# quando vai ser acionado
on:  
  # Triggers the workflow on push or pull request events but only for the main branch
  # Como vou acionar 
  push:
  #qdo tiver push no branch
    branches: [ main ]
    #qdo tiver pullrequest no branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # qdo vou acionsar manualmente
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Como vc agrupa o seu trabalho - job para build ex dev - homolog - prod
jobs:
  # This workflow contains a single job called "build"
  build:  
    # The type of runner that the job will run on
    #ond eque ele vai rodar de fato
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # o conjunto de passos que vamos usar para executar o pipeline
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # 
      # uses são actions      
      - uses: actions/checkout@v2
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore
        
      name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Dotnet Publish
        run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ${{ github.workspace }}//demo
